### PR TITLE
887 online course lp

### PR DESCRIPTION
**Pull request by alexandergimson**
As a user, so that I can access the online course, I would like to be able to visit a landing page with the videos displayed on each with a video transcription

### CODE REVIEW

**Comment by nikeshashar** [comment]
image

This doesn't look right to me

**Comment by nikeshashar** [comment]
Also the page name is weird - not something that people would look for immediately.

**Comment by alexandergimson** [comment]
I think that point isn't for people to discover it right now - we're going to test it with real life people (we'll give them the link) and once we're happy then we can make it more discoverable

**Comment by nikeshashar** [comment]
Let's add the hide from google tag in there too ?

**Comment by alexandergimson** [comment]
Great shout Nikesh!

**Comment by alexandergimson** [comment]
@roidriscoll Do you think we should have descriptions of each lesson on the lesson map page?? (/welcome) it'll help to pad out the white space and give some context about each lesson

**Comment by roidriscoll** [comment]
Yeah @alexandergimson potentially. I think a table might be worth implementing...

**Comment by nikeshashar** [comment]
@roidriscoll @alexandergimson This PR has been open for 3 weeks. Can I close it for now and you can resend it when the page is ready to go live? Or is it done now and ready for review?

**Comment by nikeshashar** [comment]
Closing as it's been open for a month now

**Pull request closed without merging**
