### PR TITLE
Removes doorbell and gets groove on the site

### LINKED ISSUE #582: Replace Doorbell with Groove

### PR DESCRIPTION
**Pull request by nikeshashar**
@pitchinvasion @sjmog can I merge this for now and then work on the CSS later? We need to get Groove implemented asap. 

Closes #582

### CODE REVIEW

**Comment by sjmog** [comment]
*unstyled

**Comment by sjmog** [comment]
I'd really prefer not. We can't be pushing unsettled things to the website, sorry.

**Comment by nikeshashar** [comment]
@sjmog Without engineering resources how do we make this happen?

**Comment by sjmog** [comment]
Honestly? I don't know. But we can't afford to let product quality slip, that's the key thing.

**Comment by sjmog** [comment]
I've added some styles to the button @nikeshashar but the contextual menu loads in a very different way, from an `iframe`. That means we can't style it. I know you mentioned we could include custom CSS, but we can't (e.g.) include our font in this, as that requires custom JavaScript. Unless this system is _absolutely critical_ and _there is literally nothing at all that can do the same thing_ this is going to be a problem: either it looks wrong (it looks horrible, very off-brand) or we have to start splitting our CSS across our local thing, Groove, and everywhere else.

At the moment we shouldn't merge this because the styles are way out from where we need to be.

**Comment by nikeshashar** [comment]
@sjmog moved this to #engineering

**Comment by nikeshashar** [comment]
This is going to be Intercom now so I'll close this

**Pull request closed without merging**
