### PR TITLE
refactors tracking.js file structure for consistency

### LINKED ISSUE #533: Fix analytics link tracking
This currently doesn't work and needs to be moved out of all.js

We also need to make sure all events have type "Course Type" => Offline

Test it in segment test environment

### PR DESCRIPTION
**Pull request by silvabox**
closes #533

### CODE REVIEW

**Comment by silvabox** [comment]
@pitchinvasion can I get a squirrel?  I'll build the bower component and deploy the changes to ronin-website after.

**Comment by pitchinvasion** [comment]
Looks good, one very quick refactor I'd add is to wrap the global functions in an object - something like

```
var Tracking = {
   clickEvents: function() {
       if (this.isAnchor)
   },
   isAnchor: function() {
  }
};
```

**Comment by silvabox** [comment]
@pitchinvasion yep - we can do that.  Any particular reason for the capital 'T' - is that a convention?

**Comment by pitchinvasion** [comment]
Yeah it indicates an object, although it's normally for a constructor function so you don't have to use it

**Comment by pitchinvasion** [comment]
:shipit:

**Pull request merged**
