### PR TITLE
622 onsite v remote landing page

### LINKED ISSUE #622: build onsite vs remote landing page

### PR DESCRIPTION
**Pull request by nikeshashar**
Closes #622 and merge into #new-comparison-partial for one merge into #master

### CODE REVIEW

**Comment by nikeshashar** [comment]
image

**Comment by jordanpoulton** [comment]
:shipit:

**Comment by sjmog** [comment]
Female discount -> womens discount @nikeshashar

**Comment by nikeshashar** [comment]
@sjmog changed - is it okay to merge?

**Comment by sjmog** [comment]
:shipit: sorry for the delay!

**Pull request merged**
