### PR TITLE
714 all case studies

### LINKED ISSUE #714: Refactoring Case Studies
- [x] Sergio
- [x] Maria
- [x] Marion
- [x] Hannah Carney
- [ ] Mara
- [x] Elia
- [ ] Sivan
- [ ] Richard W
- [ ] Wayne R
- [x] Elia B
- [ ] Van Le
- [ ] Mic 
- [ ] Daniel Ortiz
- [ ] Noah Pollock

### PR DESCRIPTION
**Pull request by nikeshashar**
Closes #714 

@Arfah Hannah C's profile ready. Merge when you get a :shipit:

### CODE REVIEW

**Comment by nikeshashar** [comment]
@Arfah @jafrog please could you merge this in so I can add the next few profiles?

**Comment by nikeshashar** [comment]
- [x] Sergio
- [x] Maria
- [x] Marion
- [x] Hannah Carney
- [ ] Mara
- [ ] Elia
- [ ] Sivan
- [ ] Richard W
- [ ] Wayne R
- [ ] Elia B
- [ ] Van Le
- [ ] Mic 
- [ ] Daniel Ortiz
- [ ] Noah Pollock

**Comment by Arfah** [comment]
@jafrog @danldb can someone please :shipit: it?

**Comment by jafrog** [comment]
:shipit:

**Comment by nikeshashar** [comment]
@alexandergimson Elia needs an image link please

**Pull request merged**
