### PR TITLE
updates Tansaku's title

### LINKED ISSUE #429: remove "head of education" term from website
copy changes to website including removing role, and reference to role in student contract etc.

### PR DESCRIPTION
**Pull request by nikeshashar**
Closes #429

### CODE REVIEW

**Comment by pitchinvasion** [comment]
:shipit: although have you double checked with @tansaku ?

**Comment by tansaku** [comment]
Should be "AI Paladin and Tiger Father" not coachineer thanks @nikeshashar :-)

**Comment by nikeshashar** [comment]
>The Paladin is a class of Warrior that is fully devoted to kindness and ridding the Universe of Evil

@tansaku are we wanting that as an explanation to your role?

**Comment by tansaku** [comment]
@nikeshashar yes - we can just adjust that to indicate that my medium for achieving those goals will be the use of "Artificial Intelligence" :-)

However I'm off this week and ideally would like to focus on this in the new year.  I want to do a full review of all website content as part of the incoming funnel review.   Not that any change needs to wait for that, but I'd like to sit down on Jan 4th and start addressing tickets/pull like these.  Is there an urgency to push this through before xmas?  Or can we look at it on Jan 4th?

**Comment by nikeshashar** [comment]
I'll close the PR. If you're reviewing the website content it would be prudent to get Arfah involved. Her strategy for the year would be based On the website so she would be most affected by this

**Pull request closed without merging**
