### PR TITLE
625 case study

### LINKED ISSUE #625: case-study

### PR DESCRIPTION
**Pull request by Arfah**
#closes #625 

Some are indented out as the pictures are not ready yet so I'll do another PR for that later.

As there is a like 10 of them to go live I thought it would make sense for someone to go over them first.

Remember any grammar/spelling - just edit it in0line!

Also added remote case studies too.

Thanks

### CODE REVIEW

**Comment by sjmog** [comment]
@Arfah I've updated the first few case studies but there are a lot of grammar, spelling, run-on sentences etc. things in the rest - I'll get to them as soon as I have some time. Would it be worth me installing some kind of CI that can spot these sorts of common mistakes?

**Comment by pitchinvasion** [comment]
@Arfah can you run this through a spell checker and fix any stuff you can spot - one tip is to read it out loud in your head and see if it sounds wrong. 

@sjmog we agreed that Arfah would fix as many of the errors herself in a spirit of continuous improvement

**Comment by sjmog** [comment]
@pitchinvasion oh sorry! I misread "Remember any grammar/spelling - just edit it in0line!" to mean, 'just go change it!'

**Comment by Arfah** [comment]
My Atom has a spell checker but it's been 20 days since I did this so I'll cast my eye over it again...

**Comment by Arfah** [comment]
@sjmog the grammar changes you made were changing the , to : but the reason I use a , and not a : is because you can't use : in yaml files. Unless there is a way around it? So i'm changing it all back.

**Comment by nikeshashar** [comment]
@Arfah :shipit: - checked and ready to go

**Pull request merged**
