### PR TITLE
Added 301 redirects for all /employers/* routes

### LINKED ISSUE #758: 301 Redirect to employers.makersacademy.com
From www.makersacademy.com/employers
And http://www.makersacademy.com/employers/contact/
Are there any employers/ pages floating around that should also be included?

### PR DESCRIPTION
**Pull request by sjmog**
Closes #758

### CODE REVIEW

**Comment by sjmog** [comment]
@nikeshashar please can you double-check this before we go with this?

**Comment by nikeshashar** [comment]
@sjmog we have `employers-faqs.yml` in the `data` folder on the main site too. Do you want to 301 that too?

**Comment by nikeshashar** [comment]
Apart from that the rest of the redirects work locally. 👍  :shipit:

**Comment by sjmog** [comment]
No, no redirect on employers-faqs as this was a one-time link sent to employers and it should keep working

**Pull request merged**
