### PR TITLE
Update magic_events.yml

### LINKED ISSUE #1096: Update Magic Page
Retrospectively adding ticket for @isoworg

### PR DESCRIPTION
**Pull request by isoworg**
@nikeshashar 👋 Closes #1096

### CODE REVIEW

**Comment by nikeshashar** [comment]
I'll check this out tomorrow and merge in 👍

**Comment by nikeshashar** [comment]
Do you have a ticket number for this @isoworg ?

**Comment by isoworg** [comment]
I don't understand the question, sorry @nikeshashar

**Comment by nikeshashar** [comment]
Did you make a ticket in our waffle for this PR to refer back to @isoworg ? At the moment its coming in from a branch on your Github

**Comment by isoworg** [comment]
No I did not - I thought that happened automagically.

**Comment by nikeshashar** [comment]
No problemo - I'll work around it this time. 

For future updates we have a contributing guide here : https://github.com/makersacademy/website/blob/master/CONTRIBUTING.md

**Comment by nikeshashar** [comment]
image

**Comment by isoworg** [comment]
@nikeshashar Please can we merge this today?

**Comment by nikeshashar** [comment]
Done :shipit:

**Comment by isoworg** [comment]
@nikeshashar I've just noticed an error, how should I go about fixing it?

**Comment by nikeshashar** [comment]
@isoworg A new ticket and PR please

**Pull request merged**
