### PR TITLE
Adds PDF

### LINKED ISSUE #834: Add LR15 ebook to site
As a marketer
So that I make our ebook offer better
I would like the book to be hosted on our site

### PR DESCRIPTION
**Pull request by nikeshashar**
Closes #834

### CODE REVIEW

**Comment by ddosque** [comment]
@nikeshashar there is nothing to squirrel here - it's a binary file?

**Comment by nikeshashar** [comment]
Yeah - it's just adding a PDF to the repo.

**Comment by nikeshashar** [comment]
I need to test it live so I can then do the routing

**Comment by ddosque** [comment]
:shipit:

**Pull request merged**
