### PR TITLE
Add 301 redirects for any /employers routes

### LINKED ISSUE #770: Redirect from /employers to employers.*
As the title suggests :)

### PR DESCRIPTION
**Pull request by sjmog**
Closes #770

### CODE REVIEW

**Comment by sjmog** [comment]
- /employers/contact goes to the new 'request a call' page on employers.makersacademy.com

**Comment by sjmog** [comment]
Self- :shipit: (yes I am ashamed)

**Comment by danldb** [comment]
@sjmog what happened here? The redirects seem fine (although I'm reminded that employers is http rather than https - I guess that is OK?)

**Comment by sjmog** [comment]
@danldb the employers page was killed Thursday, before the redirects were in place. I only just found out about it yesterday, so hastily put in some redirects.

**Pull request merged**
