### PR TITLE
466 update case studies

### LINKED ISSUE #466: update-case-studies

### PR DESCRIPTION
**Pull request by Arfah**
#closes #466 as @tansaku required a description. This is a pull request for 4 new graduate case studies that are ready to go live on the website. It would be good to get this merged by lunchtime ideally as I'd like to set up a social media campaign before the holidays start. Thanks

### CODE REVIEW

**Comment by tansaku** [comment]
:shipit: btw, Gerard has a "From" prefix on his summary, unlike anyone else - intentional?

**Comment by tansaku** [comment]
and wasn't requiring a description @Arfah :-) just saying that's good practice on issues when you open them.  I know it's difficult when busy ...

**Comment by Arfah** [comment]
Nope. I'll edit that and merge it.

And haha no worries. I shall do that from now on. :-)

**Comment by pitchinvasion** [comment]
Don't merge this yet, there's a few grammatical errors I'm fixing

**Comment by pitchinvasion** [comment]
OK :shipit: if you can re-read the stuff before doing the PR @Arfah it would be great, I think you'd have caught some of these.

@tansaku just so you know we use PRs for proof-reading as well as code reading so if you can check through the grammar etc. before adding a :shipit: I'd recommend it (I normally just make the changes inline)

**Comment by Arfah** [comment]
awesome thanks for this @pitchinvasion as always <3 Last merge of 2015 maybe! Merging it now.

**Pull request merged**
