### PR TITLE
Remove !default assignation in tabs

### LINKED ISSUE #395: Fix sass warnings
We get these every time we run tests

DEPRECATION WARNING on line 11 of /Users/leo/Code/applications/bower_components/makers_styles/source/sass/_vertical_tabs.scss:
Assigning to global variable "$medium-screen" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$medium-screen: em(640) !global !default" instead.
Note that this will be incompatible with Sass 3.2.

DEPRECATION WARNING on line 12 of /Users/leo/Code/applications/bower_components/makers_styles/source/sass/_vertical_tabs.scss:
Assigning to global variable "$base-font-color" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$base-font-color: $dark-gray !global !default" instead.
Note that this will be incompatible with Sass 3.2.

### PR DESCRIPTION
**Pull request by sjmog**
* Refills is out of date
* You shouldn't assign local variables to default over global ones

Closes #395

### CODE REVIEW

**Comment by pitchinvasion** [comment]
image

**Comment by pitchinvasion** [comment]
:shipit:

**Comment by pitchinvasion** [comment]
you my hero

**Comment by sjmog** [comment]
OK actually fixed now ;)

**Comment by pitchinvasion** [comment]
image

**Pull request merged**
