### PR TITLE
Adds Rebecca Piper

### LINKED ISSUE #895: Rebecca Piper
Add case study

### PR DESCRIPTION
**Pull request by nikeshashar**
Case study added to graduates.yml
Closes #895

### CODE REVIEW

**Comment by alexandergimson** [comment]
@nikeshashar 

blog_link: https://www.youtube.com/playlist?list=PLc4BYny7PXeQLLdl_meucEyKl8K9sI0SV

Is this correct? Her blog is a YouTube playlist?

**Comment by nikeshashar** [comment]
That's the info I got from @Arfah - she's the person who we featured on the Vlog series

**Comment by alexandergimson** [comment]
In that case it's a :shipit: from me

**Comment by nikeshashar** [comment]
Also on staging here : http://staging.makersacademy.com/case-studies/rebecca-piper/

**Pull request merged**
