### PR TITLE
more changes for the client

### LINKED ISSUE #697: fridge-raiders

### PR DESCRIPTION
**Pull request by Arfah**
#closes #697 can you look over this @nikeshashar more text changes.

### CODE REVIEW

**Comment by nikeshashar** [comment]
Just that 1 change and then good to :shipit:

**Comment by danldb** [comment]
Arfah there is a merge conflict here - do you need a hand sorting it out? Not sure if you know about merge conflicts?

**Comment by nikeshashar** [comment]
I've got it here locally on my machine @danldb - can sort it out if needed?\

**Comment by danldb** [comment]
Go for it @nikeshashar

**Comment by nikeshashar** [comment]
I'm going to merge this @Arfah - fixed the capitalization on the PR too

**Pull request merged**
