### PR TITLE
Makes logos clickable

### LINKED ISSUE #750: Clickable logos
Make onsite / remote clickable

### PR DESCRIPTION
**Pull request by nikeshashar**
Closes #750 (cc @jordanpoulton @alexandergimson)

### CODE REVIEW

**Comment by nikeshashar** [comment]
@sjmog This is based on feedback from when Mark came in and recommended we do this. Happy to kill it - just executing a list from @jordanpoulton. 

Maybe a f2f discussion would be beneficial in this case?

**Comment by jordanpoulton** [comment]
@sjmog NB that clicking the logos doesn't take you to the apply page - it takes you to a landing page that is entirely focused on onsite (/onsite) or one that's entirely focused on remote (/remote). Do you still think this changes the flow, given that they don't link to the application page? It seems intuitive to me that you an click either if you know which one is of interest, or you can scroll down if you don't know yet. Happy to huddle if that's better for chatz.

**Comment by sjmog** [comment]
Thanks for the context guys! Generally I'd say we should avoid asking customers to make a choice as soon as they hit the page - especially where it's not clear these are links or where they will go (doubly so for mobile and trebly for screen readers). Let's absolutely have those links (they're great) but how about they exist in the comparison table instead? That way we're deferring decisions, and providing context. And we can make it more obvious they're links.

Happy to go f2f if wanted

**Comment by jordanpoulton** [comment]
I'm not totally attached to having those links clickable. It came from Mark (to who's expertise I have deferred), which came from watching students interact with the site. 

If you feel really strongly against making them clickable then we can change it. I'm not super strong either way. Am v sympathetic to the impact on mobile/screen readers. 

Making the comparison table clickable is a good shout too. 

Do you think Mark was wrong with this particular suggestion?

**Comment by sjmog** [comment]
I think we were wrong with putting the logos up the top - it's not the greatest way to let people know there are two options. At the moment it suggests that you have to decide what you look at (and it doesn't do that very well either).

We should probably just remove the icons. And add some clicky bits in the comparison table :)

**Comment by nikeshashar** [comment]
Let me make that change @sjmog and see what it looks like with @alexandergimson

**Comment by nikeshashar** [comment]
Tried the price or the logo's clickable and now this looks weird to me : 

image

The difference to someone visiting our site between onsite and remote at the top of the table isn't very clear.

**Comment by sjmog** [comment]
Let's step back from this one moment. What does this funnel look like?

1. Comes to website trying to find information
2. Wants to find more information about onsite specifically
3. Cannot do so

and the similar

1. Comes to website wanting to find out about remote specifically
2. Cannot do so

How many people are in this funnel, how can we tell, etc.? If it's not many people, let's just remove the links. If it's a lot of people, let's make the logos clickable. If it's somewhere in between, let's add a dedicated partial with two routes for understanding.

I agree with you @nikeshashar I don't think clickable links in the table are obvious (or early) enough *if* there are people in the funnels

**Comment by nikeshashar** [comment]
@sjmog had a quick look at Google Analytics yesterday. We don't actually have any links to the remote page from our site at all. So someone landing on the home page has no way currently of getting to landing page - unless they come from paid traffic. There's a ticket to improve this flow somehow with #747 - we're missing quite a bit of detail on the site too for the product that could be contributing to the slump of applications for the Remote Course.

**Comment by nikeshashar** [comment]
screen shot 2016-12-05 at 18 02 36

**Comment by sjmog** [comment]
@nikeshashar that sounds logical. We should definitely add them, then. I’d suggest a special partial towards the bottom of the page? I can mock one up today if you like.

The GA screenshot appears to be for apply.makersacademy.com <http://apply.makersacademy.com/> rather than the website?

**Comment by nikeshashar** [comment]
@sjmog / @jafrog - That would be great. Our preference (Onboarding) is that we get the site updated as quickly as possible.

**Comment by nikeshashar** [comment]
screen shot 2016-12-06 at 13 34 53

@sjmog A better screenshot

**Comment by nikeshashar** [comment]
@sjmog + @anitacanita - can we sit down to discuss this please ASAP? Remote numbers are dwindling and my instinct tells me this is a factor.

**Comment by nikeshashar** [comment]
@sjmog just read your message again above : 

"This is a major flow change and it's really confusing to have two massive links with no clear indication of where they go, just going straight to 'apply'"

The links go to the landing page for each type of course not to apply. Does this make it easier to merge in for now? 

I'm currently making a remote microsite (very simple) to alleviate some of the pain of not having remote course info on the main site

**Comment by sjmog** [comment]
That’s an improvement! I’d still advocate for just removing them, though, I feel like pushing people to dedicated microsites that early in the flow is a weird idea

**Comment by nikeshashar** [comment]
The microsite links will be later in the flow - but also a direct page for marketing purposes and all customer service enquiries. 

I'll close clickable logos / links for now until further discussion ensues.

**Comment by sjmog** [comment]
Oh awesome. They sounds really helpful for direct landings and yes, I’m pro adding them later in the flow.

**Pull request closed without merging**
